name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.6.1
    - name: Restore dependencies
      working directory: /.src
       run: dotnet build --no-restore
      working directory: /.src
      run: dotnet test --no-build --verbosity normal
  
